# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import werewolf_kill_pb2 as protobufs_dot_werewolf__kill__pb2


class werewolf_killStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkRoleList = channel.unary_unary(
                '/werewolf_kill/checkRoleList',
                request_serializer=protobufs_dot_werewolf__kill__pb2.roleList.SerializeToString,
                response_deserializer=protobufs_dot_werewolf__kill__pb2.result.FromString,
                )
        self.startGame = channel.unary_unary(
                '/werewolf_kill/startGame',
                request_serializer=protobufs_dot_werewolf__kill__pb2.roleList.SerializeToString,
                response_deserializer=protobufs_dot_werewolf__kill__pb2.roleList.FromString,
                )
        self.nextStage = channel.unary_unary(
                '/werewolf_kill/nextStage',
                request_serializer=protobufs_dot_werewolf__kill__pb2.roomInfo.SerializeToString,
                response_deserializer=protobufs_dot_werewolf__kill__pb2.stage.FromString,
                )
        self.sendUserOperation = channel.unary_unary(
                '/werewolf_kill/sendUserOperation',
                request_serializer=protobufs_dot_werewolf__kill__pb2.userOperation.SerializeToString,
                response_deserializer=protobufs_dot_werewolf__kill__pb2.result.FromString,
                )
        self.voteInfo = channel.unary_unary(
                '/werewolf_kill/voteInfo',
                request_serializer=protobufs_dot_werewolf__kill__pb2.roomInfo.SerializeToString,
                response_deserializer=protobufs_dot_werewolf__kill__pb2.playerState.FromString,
                )


class werewolf_killServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkRoleList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nextStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendUserOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def voteInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_werewolf_killServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkRoleList': grpc.unary_unary_rpc_method_handler(
                    servicer.checkRoleList,
                    request_deserializer=protobufs_dot_werewolf__kill__pb2.roleList.FromString,
                    response_serializer=protobufs_dot_werewolf__kill__pb2.result.SerializeToString,
            ),
            'startGame': grpc.unary_unary_rpc_method_handler(
                    servicer.startGame,
                    request_deserializer=protobufs_dot_werewolf__kill__pb2.roleList.FromString,
                    response_serializer=protobufs_dot_werewolf__kill__pb2.roleList.SerializeToString,
            ),
            'nextStage': grpc.unary_unary_rpc_method_handler(
                    servicer.nextStage,
                    request_deserializer=protobufs_dot_werewolf__kill__pb2.roomInfo.FromString,
                    response_serializer=protobufs_dot_werewolf__kill__pb2.stage.SerializeToString,
            ),
            'sendUserOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.sendUserOperation,
                    request_deserializer=protobufs_dot_werewolf__kill__pb2.userOperation.FromString,
                    response_serializer=protobufs_dot_werewolf__kill__pb2.result.SerializeToString,
            ),
            'voteInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.voteInfo,
                    request_deserializer=protobufs_dot_werewolf__kill__pb2.roomInfo.FromString,
                    response_serializer=protobufs_dot_werewolf__kill__pb2.playerState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'werewolf_kill', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class werewolf_kill(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkRoleList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolf_kill/checkRoleList',
            protobufs_dot_werewolf__kill__pb2.roleList.SerializeToString,
            protobufs_dot_werewolf__kill__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolf_kill/startGame',
            protobufs_dot_werewolf__kill__pb2.roleList.SerializeToString,
            protobufs_dot_werewolf__kill__pb2.roleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def nextStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolf_kill/nextStage',
            protobufs_dot_werewolf__kill__pb2.roomInfo.SerializeToString,
            protobufs_dot_werewolf__kill__pb2.stage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendUserOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolf_kill/sendUserOperation',
            protobufs_dot_werewolf__kill__pb2.userOperation.SerializeToString,
            protobufs_dot_werewolf__kill__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def voteInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/werewolf_kill/voteInfo',
            protobufs_dot_werewolf__kill__pb2.roomInfo.SerializeToString,
            protobufs_dot_werewolf__kill__pb2.playerState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
