# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/werewolf_kill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotobufs/werewolf_kill.proto\"\x18\n\x06result\x12\x0e\n\x06result\x18\x01 \x01(\x08\"+\n\x08roleList\x12\x0c\n\x04role\x18\x01 \x03(\x05\x12\x11\n\troom_name\x18\x02 \x01(\t\"Q\n\tuserStage\x12\x0c\n\x04user\x18\x01 \x03(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x03(\x05\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"1\n\x08roomInfo\x12\x11\n\troom_name\x18\x01 \x01(\t\x12\x12\n\nstage_name\x18\x02 \x01(\t\"6\n\x05stage\x12\x19\n\x05stage\x18\x01 \x03(\x0b\x32\n.userStage\x12\x12\n\nstage_name\x18\x02 \x01(\t\"g\n\ruserOperation\x12\x0c\n\x04user\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\x05\x12\x0c\n\x04\x63hat\x18\x04 \x01(\t\x12\x17\n\x04room\x18\x05 \x01(\x0b\x32\t.roomInfo\"\x1c\n\x0bplayerState\x12\r\n\x05state\x18\x01 \x03(\x05\"\x07\n\x05\x65mpty2\xd4\x01\n\rwerewolf_kill\x12%\n\rcheckRoleList\x12\t.roleList\x1a\x07.result\"\x00\x12#\n\tstartGame\x12\t.roleList\x1a\t.roleList\"\x00\x12 \n\tnextStage\x12\t.roomInfo\x1a\x06.stage\"\x00\x12.\n\x11sendUserOperation\x12\x0e.userOperation\x1a\x07.result\"\x00\x12%\n\x08voteInfo\x12\t.roomInfo\x1a\x0c.playerState\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.werewolf_kill_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESULT']._serialized_start=33
  _globals['_RESULT']._serialized_end=57
  _globals['_ROLELIST']._serialized_start=59
  _globals['_ROLELIST']._serialized_end=102
  _globals['_USERSTAGE']._serialized_start=104
  _globals['_USERSTAGE']._serialized_end=185
  _globals['_ROOMINFO']._serialized_start=187
  _globals['_ROOMINFO']._serialized_end=236
  _globals['_STAGE']._serialized_start=238
  _globals['_STAGE']._serialized_end=292
  _globals['_USEROPERATION']._serialized_start=294
  _globals['_USEROPERATION']._serialized_end=397
  _globals['_PLAYERSTATE']._serialized_start=399
  _globals['_PLAYERSTATE']._serialized_end=427
  _globals['_EMPTY']._serialized_start=429
  _globals['_EMPTY']._serialized_end=436
  _globals['_WEREWOLF_KILL']._serialized_start=439
  _globals['_WEREWOLF_KILL']._serialized_end=651
# @@protoc_insertion_point(module_scope)
